FROM node:15.3.0-alpine3.10

WORKDIR /app

ENV NODE_ENV development

# hadolint ignore=DL3018
RUN apk --no-cache --upgrade add \
    gcc \
    musl-dev \
    jpeg-dev \
    zlib-dev \
    libffi-dev \
    cairo-dev \
    pango-dev \
    gdk-pixbuf \
    python3-dev \
    py3-pip \
    fontconfig \
    ttf-dejavu \
    postgresql-client \
    nano

# hadolint ignore=DL3013
RUN pip3 --no-cache-dir install wheel
# hadolint ignore=DL3013
RUN pip3 --no-cache-dir install WeasyPrint

