name: build

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: ["**"]
    types: 
      - completed
jobs:
  build-docker-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './backend/Dockerfile'
          push: false

  build-docker-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './admin/Dockerfile'
          push: false
