name: build

# on:
#   workflow_dispatch:
#   workflow_run:
#     workflows: ["unit-tests"]
#     types: 
#       - completed
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build-docker-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-backend
          key: ${{ runner.os }}-buildx-backend-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-backend
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './backend/Dockerfile'
          cache-from: type=local,src=/tmp/.buildx-cache-backend
          cache-to: type=local,dest=/tmp/.buildx-cache-backend
          push: false

  build-docker-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-admin
          key: ${{ runner.os }}-buildx-admin-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-admin
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './admin/Dockerfile'
          cache-from: type=local,src=/tmp/.buildx-cache-admin
          cache-to: type=local,dest=/tmp/.buildx-cache-admin
          push: false
