name: build

# Controls when the action will run. 
# on:
#   # # Triggers the workflow on push or pull request events
#   # push:
#   #   branches: [ "**" ]
#   # pull_request:
#   #   branches: [ "**" ]
#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
on:
  workflow_run:
    workflows: ["CI"]
    branches: ["**"]
    types: 
      - completed
jobs:
  build-docker-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './backend/Dockerfile'
          push: false
          tags: sylflo/renting-backend:latest

  build-docker-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './admin/Dockerfile'
          push: false
          tags: sylflo/renting-admin:latest
