name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
jobs:
  # eslint-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Runs eslint
  #       run: |
  #         cd backend
  #         npm i eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin
  #         npx eslint --max-warnings=0 ./src --ext .js,.jsx,.ts,.tsx
  # eslint-admin:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Runs eslint
  #       run: |
  #         cd admin
  #         npm i eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin
  #         npx eslint --max-warnings=0 ./src --ext .js,.jsx,.ts,.tsx

  # prettier-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Runs prettier
  #       run: |
  #         cd backend
  #         npx prettier --check ./src

  # prettier-admin:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Runs prettier
  #       run: |
  #         cd admin
  #         npx prettier --check ./src

  # hadolint-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: brpaz/hadolint-action@v1.2.1
  #       with:
  #         dockerfile: ./backend/Dockerfile

  hadolint-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: ./admin/Dockerfile
  
  unittest-backend:
    runs-on: ubuntu-latest
    container: node:15.7.0-alpine3.12
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: rentingtest
          POSTGRES_USER: rentingtest
          POSTGRES_DB: rentingtest
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_DATA: postgresql://rentingtest:rentingtest@postgres/rentingtest
      BASE_DIR: /__w/renting/renting/backend
      STRIPE_SK: ${{ secrets.STRIPE_SK }}
      BRAND_NAME: "My brand"
      RENTING_ADDRESS: "Emile Zola, 75003 Paris"
      LANDLORD_NAME: "John Doe"
      LANDLORD_FIRST_NAME: "John"
      LANDLORD_LAST_NAME: "Doe"
      PHONE: "+3365861456"
      MAX_PERSONS: 4
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd common
          npm i
          cd ../backend
          npm i
          npm run build
          node_modules/prisma/build/index.js migrate deploy --preview-feature
          pwd
          node ./dist/commands/admin.js "test@test.fr" "test" "test"
          npm run test customers products
