name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ master, github-actions ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-docker-admin:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './admin/Dockerfile'
          push: false
          tags: user/app:latest
  # eslint-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Runs eslint
  #       run: |
  #         cd backend
  #         npm i eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin
  #         npx eslint --max-warnings=0 ./src --ext .js,.jsx,.ts,.tsx
  # eslint-admin:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Runs eslint
  #       run: |
  #         cd admin
  #         npm i eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin
  #         npx eslint --max-warnings=0 ./src --ext .js,.jsx,.ts,.tsx

  # prettier-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Runs prettier
  #       run: |
  #         cd backend
  #         npx prettier --check ./src

  # prettier-admin:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Runs prettier
  #       run: |
  #         cd admin
  #         npx prettier --check ./src

  # hadolint-backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: brpaz/hadolint-action@v1.2.1
  #       with:
  #         dockerfile: ./backend/Dockerfile

  # hadolint-admin:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: brpaz/hadolint-action@v1.2.1
  #       with:
  #         dockerfile: ./admin/Dockerfile
