name: Publish Releases to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push-docker-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './backend/Dockerfile'
          push: true
          tags: sylflo/renting-backend:latest


  build-and-push-docker-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: './admin/Dockerfile'
          push: true
          tags: sylflo/renting-admin:latest
